name: pangeo-lectures-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - ipywidgets
  - ipykernel
  - pandas
  - xarray
  - iris
  - cartopy
  - bokeh
  - scikit-learn
  - jupyterlab
  - intake
  - intake-esm
  - s3fs
  - adlfs
  - gcsfs
  - boto3
  - awscli
  - cdsapi
  - graphviz
  - pip:
    - azureml-defaults
